/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/deskv2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[2.31, 3.74, 2.87]}
        rotation={[-Math.PI, -0.64, -Math.PI]}
        scale={[3.38, 0.29, 2.03]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[5.35, 0.29, -3.56]}
        rotation={[-Math.PI, -0.64, -Math.PI]}
        scale={[0.42, 1.69, 0.42]}
      />
      <mesh
        geometry={nodes.desk.geometry}
        material={nodes.desk.material}
        position={[0.97, 4.96, 2.38]}
        rotation={[-Math.PI, 0.94, -Math.PI]}
      />
      <mesh
        geometry={nodes.computer001.geometry}
        material={nodes.computer001.material}
        position={[2.86, 4.95, 0.69]}
        rotation={[Math.PI / 2, 0, -0.62]}
        scale={[0.35, 0.56, 0.17]}
      />
      <mesh
        geometry={nodes.computer002.geometry}
        material={nodes.computer002.material}
        position={[0.76, 5.06, 2.25]}
        rotation={[Math.PI / 2, 0, -0.62]}
        scale={[0.11, 0.11, 0.11]}
      />
      <mesh
        geometry={nodes.computer003.geometry}
        material={nodes.computer003.material}
        position={[2.04, 8.21, 2.7]}
        rotation={[Math.PI / 2, 0, -0.64]}
        scale={[0.11, 0.11, 0.11]}
      />
      <mesh
        geometry={nodes.computer004.geometry}
        material={nodes.computer004.material}
        position={[3.02, 7.22, 4.02]}
        rotation={[Math.PI / 2, 0, -0.64]}
        scale={[0.11, 0.11, 0.11]}
      />
      <mesh
        geometry={nodes.computer008.geometry}
        material={nodes.computer008.material}
        position={[2.66, 5.76, 3.53]}
        rotation={[Math.PI / 2, 0, -0.64]}
        scale={[0.11, 0.11, 0.11]}
      />
      <mesh
        geometry={nodes.keyboard.geometry}
        material={nodes.keyboard.material}
        position={[0.44, 4.53, 0.46]}
        rotation={[Math.PI / 2, 0, -0.71]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.mouse001.geometry}
        material={nodes.mouse001.material}
        position={[-1.79, 4.5, 2.43]}
        rotation={[1.53, -0.04, -0.83]}
        scale={[0.13, 0.13, 0.13]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-2.36, 0.41, -2.63]}
        rotation={[0, 0.13, 0]}
        scale={[0.25, 1.5, 0.27]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[-2.58, 3.48, -5.99]}
        rotation={[0, 0.13, 0]}
        scale={[0.12, 0.75, 0.12]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-2.36, 2.98, -4.43]}
        rotation={[0, 0.8, 0]}
        scale={[1.69, 1.18, 1.73]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-3.14, 5.26, -5.31]}
        rotation={[0, -0.76, -Math.PI / 2]}
        scale={[1.59, 1.85, 1.72]}
      />
      <mesh
        geometry={nodes.pCube171024.geometry}
        material={nodes.pCube171024.material}
        position={[-2.3, 5.78, 4.85]}
        rotation={[Math.PI / 2, 0, 2.25]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        geometry={nodes.pCube171108.geometry}
        material={nodes.pCube171108.material}
        position={[-1.99, 4.72, 4.59]}
        rotation={[Math.PI / 2, 0, 2.25]}
        scale={[0.12, 0.12, 0.12]}
      />
      <mesh
        geometry={nodes.pCube171112.geometry}
        material={nodes.pCube171112.material}
        position={[-1.94, 4.64, 4.06]}
        rotation={[Math.PI / 2, 0, 2.25]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[-2.16, 5.12, 4.49]} rotation={[1.6, 0.02, -2.47]} scale={[0.06, 0.15, 0.09]}>
        <mesh geometry={nodes.Plane003_1.geometry} material={nodes.Plane003_1.material} />
        <mesh geometry={nodes.Plane003_2.geometry} material={nodes.Plane003_2.material} />
        <mesh geometry={nodes.Plane003_3.geometry} material={nodes.Plane003_3.material} />
      </group>
      <mesh
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[6.46, 4.51, 0.23]}
        rotation={[-Math.PI, 0.71, -Math.PI]}
        scale={[0.9, 0.9, 0.9]}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[6.13, 4.59, 0.09]}
        rotation={[-Math.PI, 0.71, -Math.PI]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[5.94, 7.06, 0.01]}
        rotation={[2.25, 0.56, -1.59]}
        scale={[0.31, 0.41, 0.31]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[6.39, 7.31, 0.27]}
        rotation={[2.3, 0.49, -1.69]}
        scale={[0.31, 0.41, 0.31]}
      />
      <mesh
        geometry={nodes.Vert001.geometry}
        material={nodes.Vert001.material}
        position={[6.91, 6.09, 0.38]}
        rotation={[-2.67, 0.59, 2.86]}
        scale={[1.2, 1.2, 1.2]}
      />
    </group>
  )
}

useGLTF.preload('/deskv2.glb')
