/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/hero.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone004} />
      <primitive object={nodes.Bone024} />
      <primitive object={nodes.Bone044} />
      <primitive object={nodes.Bone064} />
      <primitive object={nodes.Bone084} />
      <primitive object={nodes.Bone104} />
      <primitive object={nodes.Bone124} />
      <primitive object={nodes.Bone144} />
      <skinnedMesh geometry={nodes.OCTOPUS.geometry} material={materials.MAIN} skeleton={nodes.OCTOPUS.skeleton} />
      <mesh
        geometry={nodes.pyramid.geometry}
        material={materials['logo gradient']}
        position={[-0.03, 3.15, 0.14]}
        scale={[-0.03, -0.02, 0.12]}
      />
      <mesh
        geometry={nodes.small_sphere.geometry}
        material={materials['Material.003']}
        position={[-0.02, 3.14, 0.14]}
        rotation={[Math.PI, -0.1, Math.PI]}
        scale={[0.22, 0.22, 0.22]}
      />
      <mesh
        geometry={nodes.electric_sphere.geometry}
        material={materials.ORB}
        position={[-0.03, 3.15, 0.14]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.crystal1.geometry}
        material={nodes.crystal1.material}
        position={[-3.34, 1.07, -1.84]}
        rotation={[Math.PI, -0.42, Math.PI]}
        scale={[-0.21, -0.48, -0.21]}
      />
      <mesh
        geometry={nodes.crystal3.geometry}
        material={nodes.crystal3.material}
        position={[-2.62, 1.04, 2.25]}
        rotation={[Math.PI, -0.42, Math.PI]}
        scale={[-0.21, -0.48, -0.21]}
      />
      <mesh
        geometry={nodes.crystal2.geometry}
        material={nodes.crystal2.material}
        position={[0.54, 0.89, -2.9]}
        rotation={[2.64, -0.28, 2.99]}
        scale={[-0.21, -0.48, -0.21]}
      />
      <mesh
        geometry={nodes.crystal8001.geometry}
        material={nodes.crystal8001.material}
        position={[-4.02, 1.15, -0.05]}
        rotation={[0.67, -0.72, 0.48]}
        scale={[-0.47, -1.07, -0.47]}
      />
      <mesh
        geometry={nodes.crystal7001.geometry}
        material={nodes.crystal7001.material}
        position={[-2.32, 1.17, -2.86]}
        rotation={[0, -0.86, 0]}
        scale={[-0.47, -1.07, -0.47]}
      />
      <mesh
        geometry={nodes.rock8.geometry}
        material={materials.rock8}
        position={[-3.34, 1.07, -1.84]}
        rotation={[Math.PI, -0.42, Math.PI]}
        scale={[-0.16, -0.35, -0.16]}
      />
      <mesh
        geometry={nodes.rock7.geometry}
        material={materials.rock7}
        position={[-2.63, 1.07, 2.23]}
        rotation={[Math.PI, -0.42, Math.PI]}
        scale={[-0.15, -0.34, -0.15]}
      />
      <mesh
        geometry={nodes.rock6.geometry}
        material={materials.rock6}
        position={[0.54, 0.91, -2.91]}
        rotation={[2.58, -0.59, 3.06]}
        scale={[0.13, 0.3, 0.13]}
      />
      <mesh
        geometry={nodes.rock1.geometry}
        material={materials.rock1}
        position={[-4.02, 1.16, -0.04]}
        rotation={[0.48, -0.31, 0.32]}
        scale={[0.3, 0.67, 0.3]}
      />
      <mesh
        geometry={nodes.rock2.geometry}
        material={materials.rock2}
        position={[-2.32, 1.17, -2.86]}
        rotation={[0, -0.86, 0]}
        scale={[-0.35, -0.78, -0.35]}
      />
      <mesh geometry={nodes.island.geometry} material={materials['ground ']} position={[-1, 0.73, -0.4]} />
      <mesh geometry={nodes.Mesh.geometry} material={materials['ground emish']} />
      <mesh
        geometry={nodes.WATER.geometry}
        material={materials.WATER}
        position={[-0.36, 0.6, 0.15]}
        rotation={[0, 0.4, 0]}
        scale={[0.08, 0.06, 0.06]}
      />
    </group>
  )
}

useGLTF.preload('/hero.glb')
