/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/human.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.68, 1.03, -2.14]} rotation={[-1.39, 1.2, 2.53]} scale={[4.17, 4.17, 4.17]}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.IK} />
        <primitive object={nodes.Rotacion} />
        <skinnedMesh
          geometry={nodes.Tentaculito001.geometry}
          material={nodes.Tentaculito001.material}
          skeleton={nodes.Tentaculito001.skeleton}
        />
      </group>
      <group position={[2.05, -0.24, 6.27]} rotation={[0.01, 0.55, 0.17]} scale={[4.17, 4.17, 4.17]}>
        <primitive object={nodes.Bone_1} />
        <primitive object={nodes.IK_1} />
        <primitive object={nodes.Rotacion_1} />
        <skinnedMesh
          geometry={nodes.Tentaculito004.geometry}
          material={nodes.Tentaculito004.material}
          skeleton={nodes.Tentaculito004.skeleton}
        />
      </group>
      <mesh
        geometry={nodes.human.geometry}
        material={nodes.human.material}
        position={[1.13, 3.05, 2.09]}
        rotation={[0.15, 0.53, -0.08]}
        scale={[2.79, 2.79, 2.79]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[0.98, 8.31, 2.06]}
        rotation={[3.13, 0, 0]}
        scale={[1.01, 1.01, 1.01]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[-4.81, 0.78, 2.29]}
        rotation={[0.01, 0.53, 1.5]}
        scale={[1.12, 1.12, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[-3.75, 2.34, 1.67]}
        rotation={[0, 0.53, 0.78]}
        scale={[2.31, 2.31, 2.31]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[1.76, 0.59, -0.99]}
        rotation={[0.02, 0.76, 0.15]}
        scale={[0.82, 0.82, 0.82]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[3.2, 0.31, -1.92]}
        rotation={[-0.07, 0.47, -1.1]}
        scale={[1.16, 1.16, 1.16]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[2.05, 1.83, -3.98]}
        rotation={[0, 0.54, -0.74]}
        scale={[2, 2, 2]}
      />
    </group>
  )
}

useGLTF.preload('/human.glb')
