/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lukáš Marek (https://sketchfab.com/Parek)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/models/6c77dfc55d34470991f77ba78fc2bdf4
title: Octopus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/octoDraco.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[0.04, 0.03, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Group24148_default_0.geometry} material={materials['default']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/octoDraco.gltf')
